backend: {}
frontend: {}
postgres: {}

externalSecrets:
  enabled: false

  aws:
    region: us-east-1
    secretName: expense-tracker/staging/db

  # ה-Secret שייווצר בתוך הקלאסטר
  targetK8sSecretName: expense-tracker-db

  # איפה מותקן External Secrets Operator (כשתרים קלאסטר)
  operator:
    namespace: external-secrets
    serviceAccountName: external-secrets

  # מיפוי keys פנימיים (בקוברנטיס) מול properties ב-JSON של Secrets Manager
  keys:
    DATABASE_USER: DATABASE_USER
    DATABASE_PASSWORD: DATABASE_PASSWORD
    POSTGRES_USER: POSTGRES_USER
    POSTGRES_PASSWORD: POSTGRES_PASSWORD
