image:
  repository: 412353803789.dkr.ecr.us-east-1.amazonaws.com/expense-tracker-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

env:
  DATABASE_URL: postgresql://expense_user:expense_pass@expense-tracker-postgres:5432/expense_db
  DATABASE_HOST: expense-tracker-postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: expense_db
  DATABASE_USER: expense_user
  DATABASE_PASSWORD: expense_pass
