frontend:
  replicaCount: 1

  image:
    repository: 412353803789.dkr.ecr.us-east-1.amazonaws.com/expense-tracker-frontend
    tag: "sha-9ce7cb6"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: nginx
    host: app.al-shak.online
    path: /
    pathType: Prefix
