{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.targetK8sSecretName | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager

  target:
    name: {{ .Values.externalSecrets.targetK8sSecretName | quote }}
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_USER
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName | quote }}
        property: {{ index .Values.externalSecrets.keys "DATABASE_USER" | quote }}

    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName | quote }}
        property: {{ index .Values.externalSecrets.keys "DATABASE_PASSWORD" | quote }}

    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName | quote }}
        property: {{ index .Values.externalSecrets.keys "POSTGRES_USER" | quote }}

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName | quote }}
        property: {{ index .Values.externalSecrets.keys "POSTGRES_PASSWORD" | quote }}
{{- end }}
